### ISSUE TITLE
Create double deployments test/production for erigon book

### ISSUE THREAD

**Issue by michelemodolo** [erigontech/docs#1]

**Comment by michelemodolo** [comment]
TBD: correctly setting up the involved subdomains of `erigon.tech`

**Comment by michelemodolo** [comment]
done:
1) every commit on `development` results to `development.erigon-documentation-preview.pages.dev/`
2) every PR merge to `main` will result to `docs.erigon.tech`

Instructed Gianni about the above,

**Comment by michelemodolo** [comment]
@bloxster Hi Gianni, I just put it "in review": if you are happy with the above this issue can be closed as "Done".

**Comment by bloxster** [comment]
Fantastic job, thank you guys for the great support!
